In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("nyc_tract_2000.csv" , sep =',')
#data = pd.read_csv("nyc_tract_2010.csv" , sep =',')
#data = pd.read_csv("brooklyn_tract_2010.csv" , sep =',')

In [2]:
#data_pre = pd.read_csv("Brooklyn_Age_Group_2011_2015.csv")
data_pre = pd.read_csv("nyc_by_age_2001_2014.csv")
pop_pre = data_pre.values
pop = data.values

In [3]:
n_area= len(data)
n_year = 15
n_age = 14

In [4]:
p = np.zeros((n_year,n_area,n_age))
pr = np.zeros((n_year,n_area,n_age))
pc = np.zeros((n_year,n_area,n_age))
r = np.zeros((n_year,n_area))
ft = np.zeros((n_year,n_age))
ftt = np.zeros(n_year)
sad = np.zeros((n_year,101))
f = np.zeros((n_year,n_area))
cf = np.zeros((n_year,n_area))
rf = np.zeros((n_year,n_area))

In [5]:
for year in range(1,15):
    for j in range(n_age):
        ft[year,j]=pop_pre[j,year]

In [6]:
pop

array([['Bronx', 1, 12780, ..., 64, 61, 32.1],
       ['Bronx', 2, 3545, ..., 163, 373, 32.7],
       ['Bronx', 4, 3314, ..., 111, 257, 32.7],
       ..., 
       ['Brooklyn', 1210, 3986, ..., 133, 261, 24.9],
       ['Brooklyn', 1214, 4384, ..., 179, 240, 24.1],
       ['Brooklyn', 1220, 2555, ..., 88, 184, 29.8]], dtype=object)

In [7]:
for i in range(n_area):
    for j in range(n_age):
        pr[0,i,j] = pop[i,j+3]        

In [424]:
pr

array([[[   0.,    0.,    0., ...,  138.,   64.,   61.],
        [ 279.,  314.,  328., ...,  151.,  163.,  373.],
        [ 244.,  313.,  299., ...,  169.,  111.,  257.],
        ..., 
        [ 354.,  463.,  488., ...,  173.,  133.,  261.],
        [ 382.,  535.,  549., ...,  188.,  179.,  240.],
        [ 216.,  236.,  253., ...,   88.,   88.,  184.]],

       [[   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        ..., 
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0.,    0.,    0.]],

       [[   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        ..., 
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0., 

In [ ]:
for year in range(1,11):
    sad[year][0] = 100
    for i in range(n_area):
        for j in range(n_age):
            pr[year,i,j] = pr[0,i,j]
            r[year,i] += pr[year,i,j]
    s=0
    for j in range(n_age):
        s+=ft[year,j]
    ftt[year] = s
    s=0
    for i in range(n_area):
        s += r[year,i]
    k = ftt[year]/s
    for i in range(n_area):
        f[year,i] = k*r[year,i]
    for i in range(n_area):
        s=0
        for j in range(n_age):
            s+=pr[year,i,j]
        s+=0.000001
        cf[year,i] = f[year,i]/s
        for j in range(n_age):
            pc[year,i,j] = cf[year,i]*pr[year,i,j]
    itr = 0
    while (itr<100):
        itr+=1
        for i in range(n_age):
            s=0
            for j in range(n_area):
                s+= pc[year,j,i]
            s+=0.000001
            rf[year,i] = ft[year,i]/s
            for j in range(n_area):
                pr[year,j,i] = rf[year,i]*pc[year,j,i]
        for i in range(n_area):
            s=0
            for j in range(n_age):
                s+=pr[year,i,j]
            s+=0.000001
            cf[year,i] = f[year,i]/s
            for j in range(1,n_age):
                pc[year,i,j] = cf[year,i]*pr[year,i,j]
        sad[year] = 0
        for j in range(n_age):
            s=0
            for i in range(n_area):
                s+=pc[year,i,j]
            s+=0.000001
            sad[year][itr]+= np.abs(ft[year,j]-s)
    for j in range(n_age):
        s=0
        for i in range(n_area):
            s+=pc[year,i,j]
        s+=0.000001
        rf[year,j]=ft[year,j]/s
    for j in range(n_age):
        s=0
        ss=0
        for i in range(n_area):
            s+=pc[year,i,j]
            pr[year,i,j] = np.floor(rf[year,j]*s)-ss
            ss +=pr[year,i,j]

In [383]:
pr[1][11] #brooklyn data

array([ 143.,  142.,  120.,  143.,  143.,  166.,  166.,  143.,  111.,
        100.,   98.,   73.,   48.,   93.])

In [367]:
pr[1][350]#nyc data

array([ 143.,  144.,  120.,  143.,  141.,  166.,  165.,  140.,  111.,
        101.,   98.,   73.,   48.,   94.])

In [368]:
p[0][350] #2010 original

array([ 139.,  142.,  120.,  151.,  140.,  162.,  160.,  141.,  110.,
        101.,   97.,   71.,   46.,   92.])

In [429]:
pr[10]

array([[   0.,    0.,    0., ...,  180.,   85.,   65.],
       [ 267.,  265.,  290., ...,  197.,  218.,  401.],
       [ 233.,  266.,  265., ...,  221.,  148.,  277.],
       ..., 
       [ 339.,  397.,  439., ...,  229.,  180.,  285.],
       [ 366.,  459.,  492., ...,  248.,  242.,  261.],
       [ 206.,  202.,  227., ...,  116.,  119.,  200.]])

In [430]:
import csv
csvfile = file('2010_predict.csv', 'wb')
writer = csv.writer(csvfile)
writer.writerows(pr[10])
csvfile.close()