In [101]:
import pandas as pd
import numpy as np
#data = pd.read_csv("nyc_tract_2000.csv" , sep =',')
data = pd.read_csv("nyc_tract_2010.csv" , sep =',')
#data = pd.read_csv("brooklyn_tract_2010.csv" , sep =',')

In [102]:
#data_pre = pd.read_csv("Brooklyn_Age_Group_2011_2015.csv")
data_pre = pd.read_csv("nyc_by_age_2001_2014.csv")
pop_pre = data_pre.values
pop = data.values

In [103]:
n_area= len(data)
n_year = 15
n_age = 14

In [104]:
p = np.zeros((n_year,n_area,n_age))
pr = np.zeros((n_year,n_area,n_age))
pc = np.zeros((n_year,n_area,n_age))
r = np.zeros((n_year,n_area))
ft = np.zeros((n_year,n_age))
ftt = np.zeros(n_year)
sad = np.zeros((n_year,101))
f = np.zeros((n_year,n_area))
cf = np.zeros((n_year,n_area))
rf = np.zeros((n_year,n_area))

In [ ]:
pop_pre

In [105]:
for year in range(1,15):
    for j in range(n_age):
        ft[year,j]=pop_pre[j,year]

ValueError: invalid literal for float(): 0-4

In [88]:
for i in range(n_area):
    for j in range(n_age):
        pr[10,i,j] = pop[i,j+3]        

In [45]:
for year in range(10,0,-1):
    sad[year][0] = 100
    for i in range(n_area):
        for j in range(n_age):
            pr[year,i,j] = pr[10,i,j]
            r[year,i] += pr[year,i,j]
    s=0
    for j in range(n_age):
        s+=ft[year,j]
    ftt[year] = s
    s=0
    for i in range(n_area):
        s += r[year,i]
    k = ftt[year]/s
    for i in range(n_area):
        f[year,i] = k*r[year,i]
    for i in range(n_area):
        s=0
        for j in range(n_age):
            s+=pr[year,i,j]
        s+=0.000001
        cf[year,i] = f[year,i]/s
        for j in range(n_age):
            pc[year,i,j] = cf[year,i]*pr[year,i,j]
    itr = 0
    while (itr<100):
        itr+=1
        for i in range(n_age):
            s=0
            for j in range(n_area):
                s+= pc[year,j,i]
            s+=0.000001
            rf[year,i] = ft[year,i]/s
            for j in range(n_area):
                pr[year,j,i] = rf[year,i]*pc[year,j,i]
        for i in range(n_area):
            s=0
            for j in range(n_age):
                s+=pr[year,i,j]
            s+=0.000001
            cf[year,i] = f[year,i]/s
            for j in range(1,n_age):
                pc[year,i,j] = cf[year,i]*pr[year,i,j]
        sad[year] = 0
        for j in range(n_age):
            s=0
            for i in range(n_area):
                s+=pc[year,i,j]
            s+=0.000001
            sad[year][itr]+= np.abs(ft[year,j]-s)
    for j in range(n_age):
        s=0
        for i in range(n_area):
            s+=pc[year,i,j]
        s+=0.000001
        rf[year,j]=ft[year,j]/s
    for j in range(n_age):
        s=0
        ss=0
        for i in range(n_area):
            s+=pc[year,i,j]
            pr[year,i,j] = np.floor(rf[year,j]*s)-ss
            ss +=pr[year,i,j]

In [383]:
pr[1][11] #brooklyn data

array([ 143.,  142.,  120.,  143.,  143.,  166.,  166.,  143.,  111.,
        100.,   98.,   73.,   48.,   93.])

In [367]:
pr[1][350]#nyc data

array([ 143.,  144.,  120.,  143.,  141.,  166.,  165.,  140.,  111.,
        101.,   98.,   73.,   48.,   94.])

In [368]:
p[0][350] #2010 original

array([ 139.,  142.,  120.,  151.,  140.,  162.,  160.,  141.,  110.,
        101.,   97.,   71.,   46.,   92.])

In [47]:
pr[1]

array([[   0.,    0.,    0., ...,  221.,   80.,   51.],
       [ 321.,  358.,  416., ...,  187.,  164.,  432.],
       [ 391.,  462.,  484., ...,  250.,  201.,  395.],
       ..., 
       [ 505.,  462.,  534., ...,  176.,  109.,  225.],
       [  91.,   92.,   95., ...,   67.,   40.,   97.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [49]:
pr[10]

array([[   0.,    0.,    0., ...,  269.,  103.,   54.],
       [ 306.,  313.,  364., ...,  232.,  215.,  459.],
       [ 372.,  405.,  425., ...,  311.,  264.,  421.],
       ..., 
       [ 481.,  410.,  474., ...,  222.,  145.,  243.],
       [  87.,   80.,   83., ...,   83.,   53.,  103.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [26]:
import csv
csvfile = file('2000_predict_backward.csv', 'wb')
writer = csv.writer(csvfile)
writer.writerows(pr[1])
csvfile.close()